[package]
name = "axum-meilisearch-mytutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
#meilisearch
meilisearch-sdk = "0.27.1"
serde = "1.0.209"
tokio = { version = "1.39.3", features = ["full"] }
#axum
axum = "0.7.5"
#.env
dotenvy = "0.15.7"
once_cell = "1.19.0"
